sonar.projectKey= GeroAlu_secure_campus
sonar.organization= geroalu
sonar.host.url=https://sonarcloud.io

sonar.projectName=secure-campus

sonar.sources=app,application
sonar.exclusions=node_modules/**,.next/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
