sonar.projectKey= GeroAlu_secure_campus
sonar.organization= geroalu
sonar.host.url=https://sonarcloud.io

sonar.projectName=secure-campus

sonar.sources=app,application
sonar.exclusions=node_modules/**,.next/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=app/hooks/**,app/lib/clients/**,app/lib/api.ts,app/store/**,app/students/components/**,app/students/page.tsx,app/layout.tsx,app/roles/page.tsx,app/page.tsx,app/Header.tsx,app/utils/permissions.ts,app/globals.css

sonar.sourceEncoding=UTF-8
